const productObj = [
    {
        item: 12664, 
        docs: "Ladies",
        vendor: "M41244",
        attr: "black",
        size: 38,
        quality: 2,
        discount: 15,
        receipt: 800,
        ext: 900,
    },
    {
        item: 12665, 
        docs: "Ladies",
        vendor: "M41244",
        attr: "white",
        size: 39,
        quality: 2,
        discount: 15,
        receipt: 800,
        ext: 900,
    },
    {
        item: 12666, 
        docs: "Ladies",
        vendor: "M41244",
        attr: "blue",
        size: 38,
        quality: 2,
        discount: 15,
        receipt: 800,
        ext: 900,
    },
    {
        item: 12667, 
        docs: "Ladies",
        vendor: "M41244",
        attr: "black",
        size: 38,
        quality: 2,
        discount: 15,
        receipt: 800,
        ext: 900,
    },
    {
        item: 12667, 
        docs: "Ladies",
        vendor: "M41244",
        attr: "black",
        size: 38,
        quality: 2,
        discount: 15,
        receipt: 800,
        ext: 900,
    },
    {
        item: 12667, 
        docs: "Ladies",
        vendor: "M41244",
        attr: "black",
        size: 38,
        quality: 2,
        discount: 15,
        receipt: 800,
        ext: 900,
    },
    {
        item: 12667, 
        docs: "Ladies",
        vendor: "M41244",
        attr: "black",
        size: 38,
        quality: 2,
        discount: 15,
        receipt: 800,
        ext: 900,
    },
]

export default productObj